use customer_behavior;
select * from customer limit 20;

-- Q1. what is the total revenue generated by male vs female customer? --
select gender, SUM(purchase_amount) as revenue
from customer 
group by gender;

-- Q2. which customer used a discount but still spent more then average purchase amount? --
select customer_id, purchase_amount
from customer
where discount_applied = 'YES' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Q3. which are the top 5 product with the highest average review rating ? --
select item_purchased, round(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average purchase Amounts between standard and Express Shipping. --
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do Subscribed customers spend more? compare average spend and total revenue between subscribe and non subscribe.
select subscription_status,
count(customer_id) as tital_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. which five products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) *100,2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. segmate customer into new, returning, and loyal based on their total number of previous purchases,and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'LOYAL'
end as customer_segment
from customer

)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment;

-- Q8.what are the top 3 most parchased products witin each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customer who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Root@123';
FLUSH PRIVILEGES;


